# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photonvision_remote-pipeline.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'photonvision_remote-pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"photonvision_remote-pipeline.proto\"E\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\r\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x1c\n\x06\x66ormat\x18\x03 \x01(\x0e\x32\x0c.ImageFormat\"c\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x0b\n\x03\x63ls\x18\x05 \x01(\r\x12\x12\n\nconfidence\x18\x06 \x01(\x02\"=\n\x10\x44\x65tectionResults\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1d\n\x07results\x18\x02 \x03(\x0b\x32\x0c.BoundingBox\"/\n\x16ObjectDetectionRequest\x12\x15\n\x05image\x18\x01 \x01(\x0b\x32\x06.Image\"=\n\x17ObjectDetectionResponse\x12\"\n\x07results\x18\x01 \x01(\x0b\x32\x11.DetectionResults*V\n\x0bImageFormat\x12\x16\n\x12\x46ORMAT_UNSPECIFIED\x10\x00\x12\x0e\n\nFORMAT_RGB\x10\x01\x12\x0f\n\x0b\x46ORMAT_GRAY\x10\x02\x12\x0e\n\nFORMAT_BMP\x10\x03\x32^\n\x16ObjectDetectionService\x12\x44\n\x0fObjectDetection\x12\x17.ObjectDetectionRequest\x1a\x18.ObjectDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photonvision_remote_pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEFORMAT']._serialized_start=385
  _globals['_IMAGEFORMAT']._serialized_end=471
  _globals['_IMAGE']._serialized_start=38
  _globals['_IMAGE']._serialized_end=107
  _globals['_BOUNDINGBOX']._serialized_start=109
  _globals['_BOUNDINGBOX']._serialized_end=208
  _globals['_DETECTIONRESULTS']._serialized_start=210
  _globals['_DETECTIONRESULTS']._serialized_end=271
  _globals['_OBJECTDETECTIONREQUEST']._serialized_start=273
  _globals['_OBJECTDETECTIONREQUEST']._serialized_end=320
  _globals['_OBJECTDETECTIONRESPONSE']._serialized_start=322
  _globals['_OBJECTDETECTIONRESPONSE']._serialized_end=383
  _globals['_OBJECTDETECTIONSERVICE']._serialized_start=473
  _globals['_OBJECTDETECTIONSERVICE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
